# Generated by Django 4.1.3 on 2023-01-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cno', models.IntegerField()),
                ('cname', models.CharField(max_length=100)),
                ('cmobile', models.IntegerField()),
                ('cemail', models.EmailField(max_length=254)),
                ('cbankname', models.CharField(max_length=30)),
                ('caccountnumber', models.IntegerField()),
                ('caccountifsccode', models.CharField(max_length=9)),
            ],
        ),
    ]
